sudo: required
dist: trusty
group: edge
services:
  - docker
language: go
go:
  - 1.8
install:
  - make bootstrap deps
script:
  - make build
after_success:
  - make image
notifications:
  email:
    recipients:
    - kiran.mova@cloudbyte.com
branches:
  except:
    - /^*-v[0-9]/      
