sudo: required
dist: trusty
group: edge
services:
  - docker
language: go
go:
  - 1.8
script:
  - make bootstrap
  - make deps
  - make build
after_success:
  - make image
notifications:
  email:
    recipients:
    - kiran.mova@cloudbyte.com
    - satyam.zode@openebs.io
branches:
  except:
    - /^*-v[0-9]/      
